### PR TITLE
implement convert functionallity based on #27

### PR DESCRIPTION
**Pull request by maxhbr**
thanks go to Helio Chissini de Castro, who is working on #27

### CODE REVIEW

**Comment by maxhbr** [comment]
annoyingly the spdx tools generate an empty file, even if they fail

**Comment by heliocastro** [comment]
@maxhbr And when the conversion parts happens ?

**Comment by maxhbr** [comment]
after verification there is a github actions step, that tries conversion: https://github.com/Open-Source-Compliance/package-analysis/pull/29/files#diff-f2bf4cd7e8b9bfd890487dd91cc81adc6c0162a2c3789840c2f9b8e0b7ccb686R37-R40

**Comment by OliverFendt** [comment]
@heliocastro does #29 contain all the required things from #27 ?

**Comment by heliocastro** [comment]
@OliverFendt Yes, i will close that PR

**Comment by OliverFendt** [comment]
@heliocastro great, thank you very much for your efforts. This is highly appreciated.

**Comment by OliverFendt** [comment]
@maxhbr, @heliocastro great work. This adds additional value to the entire repo. Well done

**Pull request merged**
