### PR TITLE
Fixed several misplaced text end tags

### PR DESCRIPTION
**Pull request by hex3262**
I wrote a small conversion program to create JSON and YAML files from all existing SPDX files and encountered this irregularity.
Signed-off-by: Carsten Emde <C.Emde@osadl.org>

### CODE REVIEW

**Review by OliverFendt — APPROVED** [review]
@hex3262 good catch, thank you very much for spotting and correcting this. However this is strange, we shall keep an eye on this, might be that this is a bug in the tooling.

**Comment by OliverFendt** [comment]
@hex3262 would you please add the Signed-off-by: Statement

**Comment by hex3262** [comment]
I just tried the experimental SPDX to JSON converter, but I'm not sure if the new files are usable. Could someone give it a try? Please do not merge!

**Comment by OliverFendt** [comment]
@ckresse would you please be so kind and test it

**Pull request closed without merging**
